apiVersion: batch/v1
kind: CronJob
metadata:
  name: parlameter-update-flow
spec:
  schedule: "10 1 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - name: run-parser-flow
            image: parlaparser-bosna
            env:
              - name: DJANGO_SETTINGS_MODULE
                value: parladata_project.settings.k8s
              - name: PARSER_MANDATE_START_DATE
                value: '2018-12-01'
            envFrom:
              - secretRef:
                  name: parladata-bosna-credentials
              - secretRef:
                  name: parlaparser-bosna-credentials
            resources:
              requests:
                memory: 1Gi
                cpu: 500m
              limits:
                memory: 1Gi
                cpu: 500m
          restartPolicy: Never
