apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: parlameter-update-flow
spec:
  schedule: "15 2 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - name: run-parser-flow
            image: parlaparser-medvode
            env:
              - name: DJANGO_SETTINGS_MODULE
                value: parladata_project.settings.k8s
              # empty parser needs just paraldata credentials
              #- name: PARSER_MANDATE_START_DATE
              #  value: '2018-12-01'
            envFrom:
              - secretRef:
                  name: parladata-credentials
              # empty parser needs just paraldata credentials
              #- secretRef:
              #    name: parlaparser-credentials
            resources:
              requests:
                memory: 400Mi
                cpu: 200m
              limits:
                memory: 400Mi
                cpu: 200m
          restartPolicy: Never
