apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlaparser-medvode
resources:
  - cronjob.yaml
images:
  - name: parlaparser-medvode
    newName: rg.fr-par.scw.cloud/djnd/parlaparser-medvode
    newTag: 'd473bfd5e7533e5fa66badd291f48dfa2f52ed20'
