apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-hrvaska
resources:
  - cronjob.yaml
images:
  - name: parlaparser-hrvaska
    newName: rg.fr-par.scw.cloud/djnd/parlaparser-hrvaska
    newTag: 'ca586afec582f4ceaa31bbbfacb92391046ead63'
