apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-medvode
resources:
  - cronjob.yaml
images:
  - name: parlaparser-medvode
    newName: rg.fr-par.scw.cloud/djnd/parlaparser-medvode
    newTag: '40415379eb2dfaaabf24a4a76310af4807a06c9e'
