apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-hrastnik
resources:
  - cronjob.yaml
images:
  - name: parlaparser-hrastnik
    newName: rg.fr-par.scw.cloud/djnd/parlaparser-hrastnik
    newTag: '0756926d05b45198f2c6d9b28bf37478b75d2dae'
