apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-trbovlje
resources:
  - cronjob.yaml
images:
  - name: parlaparser-trbovlje
    newName: rg.fr-par.scw.cloud/djnd/parlaparser-trbovlje
    newTag: '868a8f30a3bbacd5251c7b7f8f74d7cff9c9f72e'
