apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-bosna
resources:
  - cronjob.yaml
images:
  - name: parlaparser-bosna
    newName: rg.fr-par.scw.cloud/djnd/parlaparser-bosna
    newTag: '006a966d2af1813b8c597a7bc9aa42869c75193f'
