apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-medvode
resources:
  - cronjob.yaml
images:
  - name: parlaparser-medvode
    newName: rg.fr-par.scw.cloud/djnd/parlaparser-medvode
    newTag: '94531896f14a38e006f95d7753aec93c09b78fdf'
