apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-hrastnik
resources:
  - cronjob.yaml
images:
  - name: parlaparser-hrastnik
    newName: rg.fr-par.scw.cloud/djnd/parlaparser-hrastnik
    newTag: '2233caf31d442515fdbd2e64db2c1f0e463e5197'
