apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-hrvaska
resources:
  - cronjob.yaml
images:
  - name: parlaparser-hrvaska
    newName: rg.fr-par.scw.cloud/djnd/parlaparser-hrvaska
    newTag: '5ad17f07ff3be4c5d1e683e8ba7bc3754ab909db'
