apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-bosna
resources:
  - cronjob.yaml
images:
  - name: parlaparser-bosna
    newName: rg.fr-par.scw.cloud/djnd/parlaparser-bosna
    newTag: 'a164f83f1443cfbaccd7d159c9ad7d395f6834a9'
